name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD}} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t your-django-app:latest .
        working-directory: "C:\\Users\\Lenovo\\Desktop\\Docker\\221023"# Change to your project path

      - name: Push Docker Image to Docker Hub
        run: docker push your-django-app:latest kalegajanan/cicd:latest
