name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: SSH into EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC_HOST }}
          username: ${{ secrets.EC_USERNAME }}
          key: ${{ secrets.EC_SSH_KEY }}
          script: |
            # Change to your project directory on the EC2 instance
            cd djangosuccess

            # Pull the latest code from the Git repository
            #git clone
            git pull https://github.com/gajanankumar/post_cicd.git main

            # Perform any necessary setup or deployment steps (e.g., installing dependencies)
            # Restart your application server (e.g., Gunicorn, uWSGI, etc.)

            # Example for Django application:
            # systemctl restart gunicorn

