name: Django CI/CD

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t my-django-app .
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
          docker tag my-django-app:latest $DOCKERHUB_USERNAME/my-django-app:latest
          docker push $DOCKERHUB_USERNAME/my-django-app:latest

      - name: SSH into AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull my-django-app:latest
            docker stop my-django-container || true
            docker rm my-django-container || true
            docker run -d -p 80:8000 --name my-django-container my-django-app:latest
