name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    services:
      mysql:
        image: docker-mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: kale
          #MYSQL_USER: root
          #MYSQL_PASSWORD: kale
          MYSQL_DATABASE: inv
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get update
        sudo apt-get install -y libmysqlclient-dev
        MYSQLCLIENT_CFLAGS=`mysql_config --cflags` MYSQLCLIENT_LDFLAGS=`mysql_config --libs` pip install mysqlclient==2.2.0
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
